### PR TITLE
fix Getting error with serviceMonitor

### PR DESCRIPTION
**Pull request by 2005wind**
HI maintainers ,
issue detail in : https://github.com/makezbs/helm-charts/issues/2

thank you .

### CODE REVIEW

**Comment by zen** [comment]
@ingvarch any chance to get this merged? Quite an important fix

**Comment by ingvarch** [comment]
yeah, that make sense

Sorry for delay!

Thank you.

**Comment by ingvarch** [comment]
Please use version 0.1.1 - https://github.com/makezbs/helm-charts/releases/tag/query-exporter-0.1.1

**Comment by zen** [comment]
thank you @ingvarch , you just saved me from forking and creating own helm repo ;)

**Pull request merged**
